# -*- coding: utf-8 -*-
"""Copy_of_Student_Marks_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiLWOl2xqSarYUTa-BugXzsQb2EYSCmO

#**Student Marks Analyzer**

## Problem statements
In this project the marks of students are collected and stored in numpy array.The program calculates the total,average,highest,lowest.calculate the grade based on the average marks,and grade is assigned using the condition statements.

## Logic Explanation
1. It takes input from the user
2. stores marks from the list
3. laterly it converts into numpy array
4. calculate Total,average,highest,lowest.
5. calculate grade based on the average marks using if-else staements
6. finally,it prints the result
"""

import numpy as np
def student_mark(marks):
  total=np.sum(marks)
  average=np.mean(marks)
  highest=np.max(marks)
  lowest=np.min(marks)

  if average>85:
    grade='A'
  elif average>=70:
    grade='B'
  elif average>=50:
    grade='C'
  else:
    grade='Fail'


  return total,average,highest,lowest,grade

marks=[]
name=input("Enter the name of the student:")
n=int(input("Enter the number of subjects:"))
for i in range(n):
  mark=int(input(f"\nenter mark {i+1}:"))
  marks.append(mark)

marks = np.array(marks)
total,average,highest,lowest,grade=student_mark(marks)

print("\nTotal:",total)
print("Average:",average)
print("Highest:",highest)
print("Lowest:",lowest)
print("Grade:",grade)

"""## sample output
Enter the name of the student:praveena
Enter the number of subjects:4

enter mark 1:56

enter mark 2:77

enter mark 3:88

enter mark 4:74

Total: 295
Average: 73.75
Highest: 88
Lowest: 56
Grade: B

"""