# -*- coding: utf-8 -*-
"""Da_Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbztg2EnshdtfeoHH9XeObKnnPinIVDM

#Assignment 1: Python and NumPy Fundamentals

#section A:Theory Answers

1. Python

python is a high-level programming language that is easy to learn and use.It is widely used in data analysis,machine learning,and web development.

Features:

1. Simple and easy to learn the syntax
2. Python have more libraries(like Numpy,Pandas)
3. Platform independent
4. It supports multiple programming(like procedural,object-oreinted)

2. Differences

1.Mutable

* It can be changed         
* example:List           

Immutable

* It Cannot be changed
* example:string,tuple

2.List

* It uses [] (square bracket)
* It is mutable
* It is slower performance

Tuple

* It uses() (paranthesis)
* It is Immutable
* It is faster performance

3. Operators

operators are symbols used to perform operations on variables

Types:

* Arithmetic: + - * /

  eg:4+2=6

* Comparisons:> < ==
  
  eg:5>3

* Logical: and or not

  eg:(5>3 and 2<4)

* Assignment: =

  eg:x=10

4. Conditionals

conditional statements are used to make decisions in program.

* syntax

if condition:
  
    statement

elif condition:
  
    statement

* real life example:
  checking whether a student passed or failed based on marks

5. Functions

A function is a block of code that performs a specific task.

 Advantages:

* It is reusable
* It makes code easy to understand
* It reduce the code repition

6.Loops

1. For loop

* It is used for number of iteration is known

* example: Looping through list

2. While loop

* It is used for condition based

* example: run until the condition id failed

7. Numpy Basics

Numpy is a Python library used for numerical oprertions.

Why better then list:

* It is faster execution
* It uses less memory
* It supports mathematical operations

8. Slicing

Slicing is used to extract a part of a list or array.It uses indexing value.

List example:
a=[1,2,3,4,5]

print(a[4])

Output:
[2,3,4]

9.Range() Function

range() generates a sequence of numbers using the condition

* syntax:
   range(start,stop,step)

* Example:
   
   range(1,10,2)

output:
    1,3,5,7,9

10. Palindrome

A palinddrome is a number or string that reads the same string in forward and backward.

Example:
* madam
* level

Logic: Reverse the value and compare it with the original value

#Section B:Coding Answers
"""

#11.sign checker

n=int(input("Enter a number:"))

if n>0:
  print("Positive")
elif n<0:
  print("Negative")
else:
  print("Zero")

"""##Output
Enter a number:4

Positive


"""

#12.Stats function

def stats(num):
  total=sum(num)
  average=total/len(num)
  return total,average
number=[5,7,8]
print(stats(number))

"""##Output
(20, 6.666666666666667)
"""

#13.Even numbers

n=int(input("Enter a number:"))
for i in range(1,n+1):
  print(2**i)

#14.Manual Palindrome without any builtin functions

str=input("Enter a string:")
rev=""
for i in str:
  rev=i+rev
if str==rev:
  print("Palindrome")
else:
  print("Not a palindrome")

"""##Output
Enter a string:level

Palindrome

Enter a string:car

Not a palindrome

"""

#15.Numpy operation

import numpy as np
arr=np.array([10,20,30,40,50])
print("Array:",arr)
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Sum:",np.sum(arr))

"""##Output

Array: [10 20 30 40 50]
Max: 50
Min: 10
Sum: 150
"""

#16.star pattern
for i in range(5):
  print("*****")

"""## sample output
##*****
##*****
##*****
##*****
##*****
"""

#17.slincing practice

num=[1,2,3,4,5,6,7,8]
new_list=num[::2]
print("Original:",num)
print("Sliced:",new_list)

"""# Ouput
Original: [1, 2, 3, 4, 5, 6, 7, 8]

Sliced: [1, 3, 5, 7]

#Section C:Brainstorming Answers

1. Why for and While loops?

 * for loop is used for when number of iterations are known
 * while loop is used when condition is important in this loop

2. Numpy Efficiency

Numpy handles large numerical data faster than python lists because it is implemented in a low-level language like C,which is optimized for performance

3. Modularity

* code becomes more difficult
* repetition may increases
* Hard to debug

4. Logical Limits:
No,every problem cannot be solved using only condition statements.

Condition statements are used for decision-making.

5. Problem Solving

Logic building is more important than syntax memorization because programming is mainly about solving problems.
 If the person can understand the logic of a problem,they can write the solution in any programming language.Syntax can be learned and remembered,but logic helps us to develop the correct code and efficient programs
"""