# -*- coding: utf-8 -*-
"""Da_Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfbKNS310wXtzQPMdPZ861PkPJ72uHS0

#Assignnent 2:Logic Building with Python and Numpy

#Section A: Theory Answers

1. Flow of Execution

The flow of Execution means the order in which the program runs.
In python,Execution usually runs line by line from top to bottom.
Program runs step by step,but loops and conditions can change the flow of execution.

2. Importance of data types

Data types defines what kind of data a variable can store(int,float,string,etc.)

Using the correct data type is important because:

* It prevents from error
* It gives correct output

3. Role of operators

Operators are used to perform operations and make decisions in programs.

In decision-making:
* >,<,==,!= are used to compare values

Example:

If marks>50:
  
  Print("Pass")

Else:
  
  Print("Fail")

4.Internal Mechanics of for loop with range()

The range() function generates a sequence of numbers.

The for loop takes each value one by one and executes the loop.

Example:

for i in range(1,5):

  Print(i)

* range gives- 1,2,3,4
* loop runs 4 times

5. Efficiency through slicing

Slicing is used to extract parts of lists,strings,or arrays quickly.

Example:

a=[1,2,3,4,5]

Print(a[0:3])

Use cases:

* Reversing a list - a[::-1]
* Getting subset of data

6. Loop control importance

Loop control conditions decide how long a Loop runs.

It not defined properly:

* Infinite loops may occur
* Program may crash

Example:

while True:

print("Hello")

7. Numpy vs Lists

Numpy arrays are faster and use less memory compared to python lists.

* Lists - flexible but slower
* Numpy - fast and efficient

8. Problem Decomposition

Breaking a large problem into smaller functions.
It makes coding easier.

Benefits:
* It is Easy to understand
* It is easy to debug
* code reuse is possible

Example:
Student program:
* input_marks()
* calculate_average()
* display_result()

# Section B: Coding Answers
"""

#9. Sum of digits

n=int(input("Enter a number:"))
sum_digits = 0
while n>0:
  digit=n%10
  sum_digits+=digit
  n//=10
print("Sum of digits:",sum_digits)

"""Output:

Enter a number:73

Sum of digits: 10

"""

#10. Even Filter function

def even_filter(numbers):
  even_numbers=[]
  for num in numbers:
    if num%2==0:
      even_numbers.append(num)
  return even_numbers

numbers=[1,2,3,4,5,6,7,8,9,10]
print(even_filter(numbers))

"""Output:

[2, 4, 6, 8, 10]

"""

#11. Fibonacci series

n=int(input("Enter number of terms:"))
a,b=0,1
for i in range(n):
  print(a,end="")
  a,b=b,a+b

"""Output:

Enter number of terms:5
01123
"""

#12. List reversal

numbers=[int(x) for x in input("Enter numbers:").split()]
print("Orginal:",numbers)
reversed_list= numbers[::-1]
print("Reversed:",reversed_list)

"""Output:

Enter numbers:1 2 3 4 5
Orginal: [1, 2, 3, 4, 5]
Reversed: [5, 4, 3, 2, 1]
"""

#13. Numpy slicing

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
Half=arr[:len(arr)//2]
print("First half:",Half)
print("Sum:",np.sum(Half))

"""Output:

First half: [1 2 3 4 5]
Sum: 15
"""

#14. Arithmetic Palindrome

num= int(input("Enter number:"))
temp = num
rev = 0
while num>0:
  digit = num%10
  rev = rev*10+digit
  num//=10
if temp == rev:
  print("Palindrome")
else:
  print("Not a Palindrome")

"""Output:

Enter number:44

Palindrome

Enter number:54

Not a Palindrome


"""

#15. Pattern program

for i in range(1,5):
  for j in range(4):
    print(i,end="")
  print()

"""Output:

1111

2222

3333

4444

#Section C: Brainstorming

16.Pseduocode Benefits

Before coding writing pseduocode is a good practice because it helps to plan the logic clearly.
it allows the programmer to think step-by-step without worrying about syntax errors.

17. Logic Limitations

if we depends only on loops and conditional statements for every problems,the program can became complex,lengthy and difficult to understand.

18. Modular Debugging

Breaking a problem ito smaller functions helps in debugging because each function can be tested separetaly.

if an error occurs,it is easier to find and fix it in a specific function instead of checking the entire program.It also improves code readability and maintenance.

19.Slicing vs looping

slicing is more useful in real-world scenarios where we need quick access to parts of data.

Example:
* Reversing a list
* Extracting a portion of data
* working with large datasets

20.Error Analysis

understanding errors and unexpected outputs is important because it helps programmers learn from mistakes.
It improves problem solving skills and helps in writting better and more efficient code.
Debugging errors also increases confidence in programming
"""